export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const CLEAR_STATE = "CLEAR_STATE";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const MODIFY_CART_PRODUCT = "MODIFY_CART_PRODUCT";
export const CLEAN_CART = "CLEAN_CART";
